server:
  global_address: "10.19.0.168:8080"
  local_address: "0.0.0.0:8080"
  local_rounds: 3
  global_rounds: 2

strategy:
  fraction_fit: 1.0
  fraction_evaluate: 1.0
  min_fit_clients: 2
  min_evaluate_clients: 2
  min_available_clients: 2
